### ISSUE TITLE
Need improvement to FoodData API

### ISSUE THREAD

**Issue by Dragorific** [Dragorific/DePhlate_Capstone#2]
Help fix up the functionality of the FoodData API to obtain more useful information and reduce potential errors. The calls should be performed more cleanly (could be implemented with downloaded database) and present information such as; nutrients, macros, calories, fats, etc.

**Comment by aarth19** [comment]
Hey, are you there? Haha.. I know this may sound cheesy, but.. I just really love you. I love everything about you. Whenever I see you online.. I can't help but smile. Seeing you is enough to make me flustered. Seriously, how could such an angelic person such as you be my friend? I really don't deserve you. You're so perfect.. my discord kitten. I'm in love with you. You're the light of my life. Without you, I would've never been this happy. Can we talk more? I enjoy your company. Can we call more? I like listening to your voice. Can we just be with each other for a little longer? I love you so much. I'm sorry if I don't reply, discord daddy needs to do his discord mod work. But don't worry, kitten. I will reply to you ASAP. Haha.. let me get to the point. Can we be... more than friends? Can you be... more than.. just my discord kitten? I want you to be my girlfriend. If not, that's fine.. not like it matters.. haha. I respect whatever you say. But I just really want you to be my girlfriend. I can be your boyfriend.. we can get online married in the future. I'll spoil you with money from my paycheck. I'm deeply in love with you.. FUCK. I love you so much. I can't bear to part from you. I just want to hug you forever. I love your smile, your voice, your personality, your laughter, your everything. I understand if you don't want to be my girlfriend.. after all.. you are more than what I am. I'm just saying.. I can give you yearly discord nitro if you want to be my girlfriend. Honestly, at this point... what I feel is more than love. I can't explain it.. but it is deeper than the word "love." Let's just talk for a little longer. When you go offline.. I immediately miss you. I don't want to be with anyone else but you. I want us to have matching My Dress-Up Darling icons. I want to be closer to you. My darling, my kitten, the love of my life.. please be my girlfriend. I will do anything for you to be my girlfriend.. I can be your boyfriend. Fuck, I love you so much.....

**Comment by aarth19** [comment]
Still missing ~57 entries

**Comment by aarth19** [comment]
donezo funzo
